GET http://localhost:3001/api/login

### 
GET http://localhost:3001/api/login/6a529c642d28a84745bdc6c0

### 
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "nombre": "Marcos",
    "correo": "marquinho@gmail.com",
    "password": "admin"
}

### 
DELETE  http://localhost:3001/api/login/6a529c642d28a84745bdc6c0

### 
PUT http://localhost:3001/api/login/6a529ad2a6d9bf8b4b2da78b
Content-Type: application/json

{
    "nombre": "Marcos"

}